### ISSUE TITLE
Support for Serverless transformation

### ISSUE THREAD

**Issue by jaccus** [aws/aws-vsts-tools#11]
I'm trying to run my Cloud Formation template with the latest AWS Tools extension for TFS (15.117.26714.0). 

Getting the following error:

> ##[error]ValidationError: CreateStack cannot be used with templates containing Transforms.

Looks like there's no support for templates which require serverless transform:
`Transform: AWS::Serverless-2016-10-31` 

Any chance this could be fixed anytime soon?

Thanks

**Comment by normj** [comment]
To use transforms with CloudFormation you need to use changesets. You can enable that in the task by checking the "Create or update the stack using a change set" option. Be sure to have "Automatically execute the change set" check to also execute the change set. Otherwise you need to add the "AWS CloudFormation Execute Change Set" tasks.

**Comment by steveataws** [comment]
Resolving as I don't think any work is needed on the task for this. Current integration tests are creating stacks with serverless transforms and change sets without issue.
