### ISSUE TITLE
AWS Shell Script and credentials

### ISSUE THREAD

**Issue by tlund56** [aws/aws-vsts-tools#112]
Some time back I used the AWS Shell Script task together with an end-point in which I specified a Role ARN to assume. The version of the task at that point was 1.1.3. As far as I remember it worked as expected at that point. 
Now when I try it again, using both 1.1.5 and 1.1.6, it doesn't seem to properly do an assumeRole.
I'm trying to show the environment and getting AWS_ACCESS_KEY_ID=undefined.
The error I get is "An error occurred (InvalidClientTokenId) when calling the CreateRole operation: The security token included in the request is invalid.".

Using the same AWS Endpoint I can successfully do a Lambda Deployment.

Am I missing something in setting up the AWS Shell Script?

**Comment by steveataws** [comment]
Having looked over the code I think the problem lies in what happens after we get the configured credentials object, [here](https://github.com/aws/aws-vsts-tools/blob/9ddb95a521c76a9f34936ea078eb19e17b5bf061/Tasks/AWSShellScript/helpers/AWSShellScriptTaskOperations.ts#L82). Comparing to [similar code](https://github.com/aws/aws-vsts-tools/blob/9ddb95a521c76a9f34936ea078eb19e17b5bf061/Tasks/AWSCLI/helpers/AWSCliTaskOperations.ts#L62) in the AWS CLI task you can see we don't make a follow up call to force the actual credentials based on the role to be generated.

The shell script task hasn't changed since 1.1.3 so I'm puzzled as to why it now fails for you. It's possible changes elsewhere might have uncovered the bug - for example the change we made to fix the duplicate SDK bug in 1.1.6.

I'll need to do some testing to validate my theory and will get back to you when I have more information.

**Comment by cameronattard** [comment]
We're also experiencing this bug.

**Comment by steveataws** [comment]
@cameronattard noted, working on testing the fix.

**Comment by steveataws** [comment]
v1.1.7 is now released which should fix this problem for you. Resolving the issue, feel free to reopen if the new version doesn't work as expected.
