### ISSUE TITLE
AWS Lambda .NET Core Deployment

### ISSUE THREAD

**Issue by MrBeanzy** [aws/aws-vsts-tools#21]
With the AWS Lambda .NET Core Deployment step. I would like top pass precompiled code form a  build. But the only option is for "Path to Lambda Project" any suggestions?

**Comment by steveataws** [comment]
Thanks for the question. 

As you've noted, the task currently takes only the project location as it uses our .NET Core CLI extensions to perform the build, packaging and publishing process. We'll take a look to see if we can extend it to enable it to accept a pre-built package for deployment.

**Comment by steveataws** [comment]
We're thinking of extending the task so that you can supply either a project folder or the path to a pre-built zip file for deployment to the 'Path to Lambda Project' parameter. When the task detects a zip file that already exists then it simply performs the upload and deployment and skips the build. Of course if you specify a zipfile and the file doesn't exist then the task would error out.

We've used this approach in a couple of other tasks - would it work for you here?

**Comment by MrBeanzy** [comment]
That would be perfect. I have written some powershell to cover us for now. But we would defiantly prefer that as an option!

**Comment by MonneOnrust** [comment]
+1 for me for this feature request. Is there any activity on this issue? 
And could you please tell me what your view is on using builds for Lambda in VSTS? It seems to me you build, unit test and package your app and in a release you install the package on some target machine or service. Why did you build the restore and publish in a Release task?

**Comment by steveataws** [comment]
It is still on our pending backlog, waiting for someone to pick it up. Apologies for the slow response, we've lately been more focused on extending the credential support and some bug fixes - as well as prepping for our upcoming re:Invent conference.

As to the design, we were actually not sure for our v1 release what the relative usage was amongst VSTS/TFS users and separate build/release pipelines so concentrated initially on the build aspect. It so happens that the dotnet CLI extension this task uses under the covers can build and deploy in one command so that guided the implementation. Now we know users want to employ it in release pipelines without building I'll see how quickly we can bump this up our priority list.

**Comment by MonneOnrust** [comment]
Okay, that's clear. Thanks for the response. I'll wait for the next version.


________________________________

**Comment by steveataws** [comment]
v1.0.14 is now released containing a new general purpose Lambda deployment task. This task supports deployment of pre-built and packaged functions for all languages supported by Lambda. You can also use this task to deploy pre-built .NET Core functions built by our .NET Core specific Lambda task, for example in release pipelines.

HTH

**Comment by steveataws** [comment]
Resolving issue now update released. You should be able to use the existing .NET Core specific task to build your package (there's a command line option to do that and not publish) and then use the new task to perform the actual deployment to Lambda from a release pipeline. Any issues, feel free to open a new request, or to reopen this one.
