### ISSUE TITLE
Installation Issues on Agent Version

### ISSUE THREAD

**Issue by jdrharding** [aws/aws-vsts-tools#33]
Greetings,

I encountered this issue while installing the aws-vsts-tools extension on my employer's copy of TFS 2015 Update 3. The extension would always report that it had successfully installed, however, the only tool available after every installation would be the AWS CLI tool. After scouring the extension code I took a gamble and removed the 2nd (when ordered alphabetically) item's entry in the tasks list (AWSPowerShellModuleScript) from the 'tasks' section in the make-options.json file, and the corresponding entries from the 'files' and 'contributions' sections in the vss-extension.json file. Installation after these modifications worked fine.

It appears that the issue is that this tool is the only one contained in the extension requiring a different build agent version (requiring v2.115.0 where the remainder require v1.91.0). When the installation of the tool failed due to requiring a higher level agent than our installation has, it exited the installation entirely with no indication that the rest of the extension had failed to install.

I had reported this to the Microsoft team who asked me to come here for support. Is there some way to continue if a conflicting build agent version is found? Again, this would need to occur on the tools individually as the AWSPowerShellModuleScript was the only offending outlier.

Thank you.

**Comment by steveataws** [comment]
That's extremely useful information, thanks for digging in and letting us know!

[Another user](https://github.com/aws/aws-vsts-tools/issues/23) also reported that after install the S3 Upload task was awol and only the CLI task was visible but we hadn't yet come up with a cause or a resolution. We've been waiting on an email thread with Microsoft to see what diagnostics or logging might be available within VSTS/TFS to try to get further information, but haven't had a response so far. So far as install goes, it appears extension authors have no control or diagnostic available that we can turn on to help resolve issues.

Our investigation into the missing S3 task had also turned up the different agent for this PowerShell-related task, although it didn't occur to us to try removing that task since, well, it's a valid task we want to keep! The task code was originally sourced from the [vsts-tasks repo](https://github.com/Microsoft/vsts-tasks/tree/master/Tasks/powerShell) and then modified, but we kept the agent version. It might be that we can downgrade the agent version and still have it work across all the environments - I'll start testing on that now. If that doesn't work, I guess we could always restructure the extension so that tasks requiring higher minimum agent versions are listed at the end and hopefully that would work around the subsequent tasks simply disappearing. 

I'll also follow up on our email thread with Microsoft that the apparent cause has been found and suggest an enhancement that allows installation to skip over tasks that have higher agent versions that available (and report that they have done so) rather than drop the task and all subsequent ones on the floor.

**Comment by jdrharding** [comment]
Hi Steve,

Happy to help! This extension is proving very useful in automating our organization's CI/CD, a big thanks to you and your team for providing the community with these tools.

I was unsure if the higher minimumAgentVersion was there for a reason or not, so rather than tamper with it, I simply removed reference to the PS module script when packaging the VSIX and everything was fine from that point onward (other than the task in question being unavailable, of course). If you need any other information, please let me know; I'm willing to help in any way I can.

**Comment by steveataws** [comment]
Drilling further, the agent requirement for v2.115.0 was to support use of the [agent.tempDirectory](https://github.com/Microsoft/vsts-task-lib/blob/master/node/docs/minagent.md) variable. If we can fall back to some other temp location, we should be able to drop the minimum agent requirement safely.

Turns out some of our other tasks are affected in reverse - the Beanstalk and CodeDeploy tasks both use the same variable to get the temp folder and are therefore open to failing in the older TFS environments even though they declare a lower agent version.

**Comment by steveataws** [comment]
v1.0.8 has now been released, which downgrades the minimum agent version for the PowerShell task to match the others, and adapts to the presence of the Agent.TempDirectory variable based on the installed agent version. This resolves the missing tasks issue so far as we can tell from our TFS2015 install setup.

Resolving issue; feel free to reopen if you still encounter issues.
