### ISSUE TITLE
AWS CLI task leaves credentials on agents

### ISSUE THREAD

**Issue by cameronattard** [aws/aws-vsts-tools#38]
I've just noticed that there doesn't seem to be any post-job cleanup, meaning the ~/.aws/credentials file remains on the agent after the job has completed. This is not ideal for use-cases where several teams are using the same build agent pools with different AWS IAM requirements.

**Comment by steveataws** [comment]
I have to admit, since I do some of my dev work for the tools on a TFS instance on my laptop I'm not a fan of the CLI or PowerShell tasks updating my credential profiles so am looking at switching both tasks over to using environment variables. I don't have an ETA for release right now, but hopefully soon. Treating this as a bug :-)

**Comment by steveataws** [comment]
This is now implemented (for the AWS CLI task, the PowerShell task will come later as it's a bit more involved). The change should ship in the update we are planning to release next week.

**Comment by cameronattard** [comment]
Awesome, thanks again for your great work on these tools!

**Comment by steveataws** [comment]
v1.0.14 is now released, with updates to the two command line tool tasks to use environment variables instead of credential profiles.

HTH

**Comment by steveataws** [comment]
Resolving issue now update released.
