### ISSUE TITLE
DOS Fileformat convertion

### ISSUE THREAD

**Issue by jonasjuni** [aws/aws-vsts-tools#52]
Hello guys, it's my first issue report and forgive me any mistake!

I don't know why aws-vsts tool is converting my files to DOS format, this is an exemple using code deploy in a Linux server:

<a href="https://imgur.com/5qvB9T4"><img src="https://i.imgur.com/5qvB9T4.png" title="source: imgur.com" /></a>
DOS line endings 

The same file, but now cloned straight from the VSTS git repository:
<a href="https://imgur.com/5cAuZtH"><img src="https://i.imgur.com/5cAuZtH.png" title="source: imgur.com" /></a>

it may be a MS issue when the files are compressed, is there anyone else having the same problem?

Thanks

**Comment by steveataws** [comment]
I think this is actually happening when VSTS/TFS checks out your files from the source repo. I encountered the same issue a few days ago when I uploaded files intended for a Linux EC2 instance into my repo and ran a build - the files in the build agent's work area had CR/LF line endings. Initially this was due to my core.autocrlf settings when I checked them in from my Windows laptop but even after correcting the files and re-committing, subsequent builds in the workarea shows Windows line terminations, not Unix ones.

The workaround I used was to add a .gitattributes file to my repo to control the files that checkout should not perform line terminator translation against.

**Comment by jonasjuni** [comment]
Thanks Steve, I will use the same workaround! as it seems to be a VSTS problem, should I close this issue?

**Comment by steveataws** [comment]
Sure, if you're happy you have enough info to proceed. If you still hit problems, feel free to reopen.

From the perspective of the CodeDeploy task, it zips the files up in the workarea as-is. It never actually opens or otherwise processes the files.

**Comment by jonasjuni** [comment]
All good Steve,

I've added a 
.gitattributes:
`*	text eol=lf`

I'll try to find a better approach, but it's working 
Cheers!

**Comment by jonasjuni** [comment]
I've found another solution as reported here: [https://github.com/Microsoft/vsts-tasks/issues/5682](url)...

<a href="https://imgur.com/DO0ZAHR"><img src="https://i.imgur.com/DO0ZAHR.png" title="source: imgur.com" /></a>

Using a Linux agent to deploy my application...
Many thanks!
