### ISSUE TITLE
Deploy with Codedeploy task

### ISSUE THREAD

**Issue by andyjcooper** [aws/aws-vsts-tools#55]
With the Deploy with Codedeploy task is there a way to use S3 encryption (AES256) as part of the zip file upload? Our AWS environment prevents uploading a file to S3 unless you use AES 256 which is causing the Codedeploy task to fail. As a test we can use the S3 Upload task fine as this supports AES 256 encryption. If we remove the AES 256 encryption setting from the S3 Upload task it also fails.

Many thanks

**Comment by steveataws** [comment]
There's not currently a way inside the CodeDeploy task itself. 

We could extend the task to include all the encryption options from the S3 Upload task, but that would add quite a bit of complexity to the task configuration (although I guess we could put them into a section and collapse it by default). There are a bunch of other tasks (eg Beanstalk deployment) that also do S3 uploads on behalf of the build - if we start to copy the encryption settings in there too, things really start to bloat.

Since the S3 Upload task already handles the encryption part of things, how about if we extended the CodeDeploy task (and others where relevant) with an option to indicate the bundle already exists in S3 due to a prior upload? Would that work for you?

**Comment by andyjcooper** [comment]
Hi Steve,

Thanks for the speedy reply.

Yes that would be perfect.

Many thanks
Andy

**Comment by steveataws** [comment]
Working on it :-)

**Comment by andyjcooper** [comment]
Awesome, many thanks Steve.

**Comment by steveataws** [comment]
I've just released v1.0.17 to the marketplace with the update. The CodeDeploy task now contains an option allowing you to specify the deployment bundle should come from a folder or file in the build workspace (the default option) or from a previously uploaded archive in S3.

Hope this does what you need; if so I'll extend the support to the Elastic Beanstalk task too.

**Comment by andyjcooper** [comment]
Hi Steve,

I've tested this out and is all working! Many thanks for your help in getting this updated so quickly.

Cheers
Andy

**Comment by steveataws** [comment]
Good to know, I'll get this extended to the Beanstalk task too. Resolving :-)
