### ISSUE TITLE
IAM InstanceProfile support for credentials

### ISSUE THREAD

**Issue by croomshine** [aws/aws-vsts-tools#63]
Any plans to support IAM InstanceProfile credentials instead of static AK/SK?  We run VSTS agents on ec2 instances and would be great to those credentials instead of statically creating them in VSTS.

**Comment by steveataws** [comment]
We're certainly thinking about that scenario.

Last time I played around with different auth types in the VSTS sdk, it looked like we'd have to set up a type containing a single option that when checked would set the tools to use instance profile credentials as otherwise the auth type would have no fields, and this didn't seem to work. This felt more than a little clunky so instead I've been considering dropping the 'required' attribution on the credential and region settings for each task. 

If credentials and region are set for a task then they obviously get used, otherwise the task would drop back to trying to get credential and region data from the environment, which could be in the form of environment variables or an instance profile if running on EC2. If no credentials or region could be established then the task would error out eventually. Its also nicely backwards compatible and super quick to implement :-)

Any thoughts on the approach for your scenario?

**Comment by croomshine** [comment]
Thanks for the quick response!  Here is how we currently have VSTS agents setup within our AWS accounts.

1.  There is a ec2 server running in a central "deployment" account.  This AWS account only runs ec2 servers with VSTS agents and assumes role into other accounts to do deployment activities like creating ASG or ELBs.  It never deploys anything within the same account as the ec2 instance.  It also does cross region, so the ec2 running in us-east-1 will assume role into another account and deploy into eu-central-1.

2.  There is a ec2 server running in a "shared" account that does inter-vpc and same account and region deployments.  It's mainly there to access resources inside the VPC as well as any AWS resources running within the same account.

With that said, does it still make it simple to implement?  I think it would be fine to create a VSTS Credential object for each of these scenarios, then choose the credentials we want in the task, as well as select the region to use.  Typically we set region through release or build variable.  Maybe setting AK/SK to value IAM and then if ak or sk == IAM, then do not set credentials.  I looked at the Azure Classic credential setup and it has radio and dropdown inputs, which could work here but not sure the effort to implement.

Looking at the modal popup for credentials, only one I see missing is the cross account text box?

Thanks again!

**Comment by cameronattard** [comment]
Falling back to instance profile would be perfect for us!

**Comment by JeffRausch** [comment]
Any update with this?  We would like to simply use the role attached to the EC2 instance that we have the VSTS agents running on.  This would make it a lot easier to manage.

**Comment by steveataws** [comment]
I'd made a start but had to switch away to other work that suddenly became a higher priority. Hoping to get back to the changes shortly.

Handling credentials is easy since the AWS SDK for Node.js handles the fallback to environment variables or the EC2 instance metadata for the tasks. It doesn't handle auto-detection of region from EC2 instance metadata though so that's something I still need to code up.

**Comment by steveataws** [comment]
As it's been a while I thought I'd give some news :-)

This work is now pending release, which we hope will not be more than a few weeks out. When released you will be able to configure credentials explicitly (as you do today), via environment variables on the build host or, if the build host is an EC2 instance, the tasks will automatically get credentials and region if needed from the EC2 instance metadata.

**Comment by steveataws** [comment]
Resolving,  included in v1.1.0 released Aug 2nd.
